# Generated by Django 5.1.3 on 2025-11-10 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="jersey_number",
            field=models.PositiveSmallIntegerField(
                default=99,
                help_text="Jersey number (1–99). Must be unique within the same team.",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["team", "jersey_number"], name="idx_team_jersey"
            ),
        ),
        migrations.AddConstraint(
            model_name="player",
            constraint=models.UniqueConstraint(
                fields=("team", "jersey_number"), name="unique_jersey_per_team"
            ),
        ),
    ]
