# Generated by Django 5.1.3 on 2025-01-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='league_id',
        ),
    ]
