# Generated by Django 5.1.3 on 2025-11-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_player_jersey_number_alter_player_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("short_code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="stats",
            name="game",
        ),
        migrations.RemoveField(
            model_name="stats",
            name="player",
        ),
        migrations.CreateModel(
            name="PlayerGameStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.game"
                    ),
                ),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.metric"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.player"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PlayerMetric",
        ),
        migrations.DeleteModel(
            name="Stats",
        ),
        migrations.AddIndex(
            model_name="playergamestat",
            index=models.Index(
                fields=["game", "player"], name="core_player_game_id_dd455e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playergamestat",
            index=models.Index(
                fields=["metric"], name="core_player_metric__37edb0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playergamestat",
            constraint=models.UniqueConstraint(
                fields=("game", "player", "metric"), name="unique_player_stat_per_game"
            ),
        ),
    ]
