# Generated by Django 5.1.3 on 2025-11-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_metric_remove_stats_game_remove_stats_player_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
